package main

import (
	"flag"
	"fmt"
)
2-
func main() {
	host := flag.String("host", "localhost", "Server host address")
	port := flag.Int("port", 8080, "Port to run the server on")
	debug := flag.Bool("debug", false, "Enable debug mode for verbose logging")
	flag.Parse()
	
	fmt.Println("=== CLI TOOL CONFIGURATION ===")
	fmt.Printf("Host  : %s\n", *host)
	fmt.Printf("Port  : %d\n", *port)
	fmt.Printf("Debug : %v\n", *debug)

	args := flag.Args()
	if len(args) > 0 {
		fmt.Println("\n=== UNPARSED ARGUMENTS ===")
		for i, arg := range args {
			fmt.Printf("Arg[%d]: %s\n", i, arg)
		}
	} else {
		fmt.Println("\nTip: Try running this tool with additional commands")
	}
}

/*
1. View help menu (automatically generated by Go):
	go run 2-Parse-Flags.go -h

2. Run with custom flags:
	go run 2-Parse-Flags.go --port=9090 --debug=true

3. Run with flags and trailing arguments:
	go run 2-Parse-Flags.go --host=127.0.0.1 start worker
*/